const PRIVATE_DURATION = 45;
const GROUP_DURATION = 60;
const STEP = 15;
const MAX_GROUP_SIZE = 6;
const MAX_STUDENTS = 30;

export { MAX_GROUP_SIZE, PRIVATE_DURATION, GROUP_DURATION, STEP, MAX_STUDENTS };
